#######################################
#####            http            #####
######################################
server:
  address: 0.0.0.0
  port: 9090
#######################################
#####           consul           #####
######################################
spring:
  application:
    name: service-monitor
  cloud:
    consul:
      discovery:
        health-check-url:  http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
        health-check-critical-timeout: 60s
        health-check-interval: 10s
        prefer-ip-address: true
      host: 192.168.0.200
      port: 8500
    loadbalancer:
      retry:
        enabled: true
#######################################
#####            监控            #####
######################################
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#######################################
#####           aliyun           #####
######################################
aliyun:
  key: 123*123
  secret: 123*123
  sms-signature: 123
  sms-templates:
    zh: 123*123
    en: 123*123
  email:
    from: 123*123
    alias: 123*123
    tag:123*123
twilio:
  key: 123456
  secret: 123456
  from: 123*123
#######################################
#####            para            #####
######################################
# service.para: service-monitor
service.para: getu-gateway
send:
  email: 106***3360@qq.com
  region: 86
  mobile: ********
